### ISSUE TITLE
Breadcrumbs point to README.md instead of index.md

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit#4]
The link "Home" in the breadcrumbs points to https://undp-accelerator-labs.github.io/national_innovation_ecosystems_toolkit/README.html. However, the link we have been circulating (https://undp-accelerator-labs.github.io/national_innovation_ecosystems_toolkit/#) resolves to the `index.md` file. This forces us to maintain two identical copies of the home page. 

Can this be fixed, so that we can get rid of one of the files?  

![image](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/assets/1976806/77f9f559-a6ef-4a45-b72f-192d06a88235)

**Comment by thisdapo** [comment]
The breadcrumb has been fixed to point to the index.md file.
