### ISSUE TITLE
Correcting errors in the menu

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit#6]
(Sorry – I realized direct editing of the files has been disabled. Hence, I have to open an issue.) 

@thisdapo 

1. [This file](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/blob/main/Understanding%20and%20pitching%20NIE/National%20Innovation%20ecosystem%20talking%20points%20and%20value%20proposition/Factsheet.md) should be titled `Pitching for NIEs and PSI`, rather than, as now, `National Innovation Ecosystem Toolkit`. When I say "titled" I refer to the navigation menu (see screnshot below). 
2. [This file](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/blob/main/Understanding%20and%20pitching%20NIE/Understanding%20NIE%20and%20PSI/Factsheet_understanding_NIE_PSI.md) should be titled `Understanding National Innovation Ecosystems (NIEs) and Public sector innovation (PSI)` with the "s" at the end of "Ecosystems" and "NIEs", following the English convention  on pluralizing acronyms. When I say "titled" I refer to *both* the navigation menu and the title of the page itself.
3. [The parent file](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/blob/main/Understanding%20and%20pitching%20NIE/README.md) should be titled `Understanding and pitching NIEs`, with the final "s".
4. The order of the two menu items under `Understanding and pitching NIEs` should be reversed: first should come "understanding", second "pitching".

![image](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/assets/1976806/d923ff34-b83a-4f20-9bbb-552d8f6035ef)

**Comment by this-pama** [comment]
Fixed.
