### ISSUE TITLE
Add a "Team" page and contributors pages

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit#7]
The file `contributors_information.md` contains the information I have (but not the pictures). We need to link each contributor's (dynamic) page from their names on the tool pages. We also need a "Team" page accessible as a top-level item from the menu, where to put the summary of contributors, currently in the "Background" page.

**Comment by this-pama** [comment]
The team's profile is now prepared, and you can view a sample by clicking [here](https://undp-accelerator-labs.github.io/national_innovation_ecosystems_toolkit/Team.html). To get an idea of a contributor's profile page, take a look at the example found [here](https://undp-accelerator-labs.github.io/national_innovation_ecosystems_toolkit/contributors/Jane-doe.html).

The contributors' information is populated from the YAML file [here](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/blob/main/_data/contributors.yml). Kindly keep it up to date to represent the details of the contributors. Currently, it is using dummy data.

Moreover, the images for the contributor's profiles should be uploaded [here](https://github.com/UNDP-Accelerator-Labs/national_innovation_ecosystems_toolkit/tree/main/public/imgs/contributors), and remember to link the corresponding image within the contributor's YAML file. 
This is ready with #8 

@albertocottica
